export const SocketEvent = {
  SendMessage: 'message',
  UserOnline: 'user-online',
  ReceiveMessage: 'emit-message',
};

export const Symptomps = [
  'itching',
  'skin_rash',
  'nodal_skin_eruptions',
  'continuous_sneezing',
  'shivering',
  'chills',
  'joint_pain',
  'stomach_pain',
  'acidity',
  'ulcers_on_tongue',
  'muscle_wasting',
  'vomiting',
  'burning_micturition',
  'spotting_urination',
  'fatigue',
  'weight_gain',
  'anxiety',
  'cold_hands_and_feets',
  'mood_swings',
  'weight_loss',
  'restlessness',
  'lethargy',
  'patches_in_throat',
  'irregular_sugar_level',
  'cough',
  'high_fever',
  'sunken_eyes',
  'breathlessness',
  'sweating',
  'dehydration',
  'indigestion',
  'headache',
  'yellowish_skin',
  'dark_urine',
  'nausea',
  'loss_of_appetite',
  'pain_behind_the_eyes',
  'back_pain',
  'constipation',
  'abdominal_pain',
  'diarrhoea',
  'mild_fever',
  'yellow_urine',
  'yellowing_of_eyes',
  'acute_liver_failure',
  'fluid_overload',
  'swelling_of_stomach',
  'swelled_lymph_nodes',
  'malaise',
  'blurred_and_distorted_vision',
  'phlegm',
  'throat_irritation',
  'redness_of_eyes',
  'sinus_pressure',
  'runny_nose',
  'congestion',
  'chest_pain',
  'weakness_in_limbs',
  'fast_heart_rate',
  'pain_during_bowel_movements',
  'pain_in_anal_region',
  'bloody_stool',
  'irritation_in_anus',
  'neck_pain',
  'dizziness',
  'cramps',
  'bruising',
  'obesity',
  'swollen_legs',
  'swollen_blood_vessels',
  'puffy_face_and_eyes',
  'enlarged_thyroid',
  'brittle_nails',
  'swollen_extremeties',
  'excessive_hunger',
  'extra_marital_contacts',
  'drying_and_tingling_lips',
  'slurred_speech',
  'knee_pain',
  'hip_joint_pain',
  'muscle_weakness',
  'stiff_neck',
  'swelling_joints',
  'movement_stiffness',
  'spinning_movements',
  'loss_of_balance',
  'unsteadiness',
  'weakness_of_one_body_side',
  'loss_of_smell',
  'bladder_discomfort',
  'foul_smell_ofurine',
  'continuous_feel_of_urine',
  'passage_of_gases',
  'internal_itching',
  'toxic_look_(typhos)',
  'depression',
  'irritability',
  'muscle_pain',
  'altered_sensorium',
  'red_spots_over_body',
  'belly_pain',
  'abnormal_menstruation',
  'dischromic_patches',
  'watering_from_eyes',
  'increased_appetite',
  'polyuria',
  'family_history',
  'mucoid_sputum',
  'rusty_sputum',
  'lack_of_concentration',
  'visual_disturbances',
  'receiving_blood_transfusion',
  'receiving_unsterile_injections',
  'coma',
  'stomach_bleeding',
  'distention_of_abdomen',
  'history_of_alcohol_consumption',
  'fluid_overload',
  'blood_in_sputum',
  'prominent_veins_on_calf',
  'palpitations',
  'painful_walking',
  'pus_filled_pimples',
  'blackheads',
  'scurring',
  'skin_peeling',
  'silver_like_dusting',
  'small_dents_in_nails',
  'inflammatory_nails',
  'blister',
  'red_sore_around_nose',
  'yellow_crust_ooze',
  'prognosis',
];

export const ArticleStaticData = [
  {
    id: 1,
    link: 'https://suckhoedoisong.vn/tphcm-van-dong-tiem-vaccine-covid-19-cho-hoc-sinh-qua-facebook-zalo-tiktok-169221213075148389.htm',
    thumbnail:
      'https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2022/12/13/hoc-sinh-tiem-vaccine-covid-19-tr-16708923371472087160942.jpg',
    title:
      'TP.HCM vận động tiêm vaccine COVID-19 cho học sinh qua Facebook, Zalo, TikTok',
    subTitle: 'Tin nóng y tế',
    description:
      'SKĐS - Sở GD&ĐT TP.HCM yêu cầu lãnh đạo các đơn vị trường học xây dựng kế hoạch cụ thể thực hiện công tác tuyên truyền, vận động cha mẹ học sinh đồng thuận cho con em tham gia tiêm vaccine trong năm học 2022-2023.',
  },
  {
    id: 2,
    link: 'https://suckhoedoisong.vn/dich-sot-xuat-huyet-tang-nhieu-ca-nang-bac-si-keu-goi-nguoi-du-suc-khoe-tich-cuc-hien-tieu-cau-16922121216512192.htm',
    thumbnail:
      'https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2022/12/12/ha-thanh12-1670838407570749276133.jpeg',
    title:
      'Dịch sốt xuất huyết tăng, nhiều ca nặng, bác sĩ kêu gọi người đủ sức khoẻ tích cực hiến tiểu cầu',
    subTitle: 'Sốt xuất huyết',
    description:
      'SKĐS - Trong bối cảnh dịch sốt xuất huyết vẫn đang rất phức tạp với nhiều ca bệnh nặng, Ban tổ chức Chủ nhật Đỏ mong muốn những người đủ điều kiện sức khỏe hãy tích cực tham gia hiến tiểu cầu theo nhu cầu của các cơ sở y tế.',
  },
  {
    id: 3,
    link: 'https://suckhoedoisong.vn/bo-y-te-cong-bo-quyet-dinh-bo-nhiem-bo-nhiem-lai-lanh-dao-tai-cac-don-vi-thuoc-bo-169221212154238232.htm',
    thumbnail:
      'https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2022/12/12/3m7a1066-16708344386411285280133.jpg',
    title:
      'Bộ Y tế công bố quyết định bổ nhiệm, bổ nhiệm lại lãnh đạo các đơn vị thuộc Bộ',
    subTitle: 'Bộ y tế',
    description:
      'SKĐS - Chiều ngày 12/12, tại Bộ Y tế, Bộ trưởng Bộ Y tế Đào Hồng Lan đã trao quyết định bổ nhiệm, bổ nhiệm lại Lãnh đạo Cục Quản lý Môi trường Y tế, Vụ Tổ chức cán bộ, Văn phòng Bộ Y tế, Trung tâm Truyền thông - Giáo dục sức khoẻ TW và Cục Y tế dự phòng.',
  },
  {
    id: 4,
    link: 'https://suckhoedoisong.vn/hon-2500-phan-qua-giang-sinh-am-ap-tang-cac-benh-nhi-169221210204654717.htm',
    thumbnail:
      'https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2022/12/10/tre-em-16706798433341898967698.jpg',
    title: 'Hơn 2.500 phần quà giáng sinh ấm áp tặng các bệnh nhi',
    description:
      'SKĐS - Những gương mặt trẻ thơ dù có em đang ngồi xe lăn, có em tay vẫn cắm kim truyền thuốc, có em đã ở bệnh viện vài tháng chữa về nhà... háo hức vui cười khi được nhận phần quà ấm áp trong mùa giáng sinh đặc biệt tại Bệnh viện Nhi TW...',
    subTitle: 'Súc khỏe trẻ em',
  },
  {
    id: 5,
    link: 'https://suckhoedoisong.vn/ty-so-gioi-tinh-khi-sinh-cua-ha-noi-uoc-dat-1125-tre-trai-100-tre-gai-169221209215022788.htm',
    thumbnail:
      'https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2022/12/9/gioi-tinh-1670597106747225462575.jpeg',
    title:
      'Tỷ số giới tính khi sinh của Hà Nội ước đạt 112,5 trẻ trai/100 trẻ gái',
    subTitle: 'Y tế & Giới tính',
    description:
      'SKĐS - Hà Nội đã bước đầu kiểm soát được mất cân bằng giới tính khi sinh. Tỷ số giới tính khi sinh (số trẻ trai/100 trẻ gái) năm 2022 ước đạt 112,5 trẻ trai/100 trẻ gái.',
  },
  {
    id: 6,
    link: 'https://suckhoedoisong.vn/bo-y-te-bai-bo-quy-dinh-gay-kho-trong-dau-thau-trang-thiet-bi-y-te-169221209003008029.htm',
    thumbnail:
      'https://suckhoedoisong.qltns.mediacdn.vn/324455921873985536/2021/8/3/trang-thiet-bi-16280042476611755813414.jpg',
    title: 'Bộ Y tế bãi bỏ quy định gây khó trong đấu thầu trang thiết bị y tế',
    subTitle: 'Y tế & Vật tư',
    description:
      'SKĐS - Tại Thông tư số 14/2022/TT-BYT do Bộ Y tế vừa ban hành, quy định các đơn vị phải tham khảo giá trang thiết bị y tế trúng thầu trong vòng 12 tháng trước và không được cao hơn giá trúng thầu của trang thiết bị y tế đó đã được bãi bỏ.',
  },
];
